const ADDNEWCONTACT = "ADD_NEW_CONTACT";
const DELETECONTACT = "DELETE_NEW_CONTACT";
const SETFILTER = "FILTER_CONTACT";
const SETALERT = "ALERT_CONTACT"

export { ADDNEWCONTACT, DELETECONTACT, SETFILTER, SETALERT }